name          'example42-quagga'
version       '3.0.0'
source        'www.example42.com'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages quagga'
description   'Based on stdmod/puppet-skeleton-standard 0.0.5.'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
